network:
  wifis:
    wlan0:
      dhcp4: yes
      access-points:
        "eduroam":
          auth:
            key-management: eap
            method: peap
            identity: "harwe006@umn.edu"
            password: "One does not beg the sun for mercy"
            ca-certificate: "/home/jharwell/.cat_installer/ca.pem"
  