# sudo apt update && sudo apt install curl gnupg2 lsb-release
- name: Install dependencies for setting up sources
  ansible.builtin.apt:
    name:
      - curl
      - gnupg2
      - lsb-release
      - python3-apt   # ansible.builtin.apt_repository would try to install this later
    update_cache: yes
  become: yes

# curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
- name: Setup ROS1 keys
  ansible.builtin.apt_key:
    url: '{{ ros1_gpg_key_url }}'
    state: present
  become: yes

# sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros1-latest.list'
- name: Setup ROS1 sources
  ansible.builtin.apt_repository:
    repo: deb {{ ros1_repository_url }} {{ ansible_distribution_release }} main
    state: present
    filename: ros1-latest
  become: yes

- name: Update apt cache with new sources
  ansible.builtin.apt:
    update_cache: yes
  become: yes
