# Only enabled for the ubuntu user by default.
- name: Passwordless sudo
  become: yes
  lineinfile:
    path: /etc/sudoers.d/90-cloud-init-users
    insertafter: EOF
    line: "{{ ansible_user_id }} ALL=(ALL) NOPASSWD:ALL"

- name: Ensure group "i2c" exists
  become: yes
  ansible.builtin.group:
    name: i2c
    state: present

- name: Add {{ ansible_user_id }} to dialout,i2c
  become: yes
  user:
    name: '{{ ansible_user_id }}'
    groups: dialout,i2c
    append: yes
