---
 - name: Pull project updates to nodes
   hosts: [all]
   tasks:
     - name: Get turtlebot config
       include_vars: vars/turtlebot-config.yaml
       when: inventory_hostname in groups['turtlebots']

     - name: Get develserver config
       include_vars: vars/develserver-config.yaml
       when: inventory_hostname in groups['develservers']

     - name: Lookup ROS1 config
       ansible.builtin.include_vars:
         file: vars/ros1-config.yaml

     - name: Pull and rebase RCSW
       ansible.builtin.git:
         repo: https://github.com/swarm-robotics/rcsw.git
         dest: "{{ research_root }}/rcsw"
         update: yes
         version: devel

     - name: Pull and rebase RCPPSW
       ansible.builtin.git:
         repo: https://github.com/swarm-robotics/rcppsw.git
         dest: "{{ research_root }}/rcppsw"
         update: yes
         version: devel

     - name: Pull and rebase COSM
       ansible.builtin.git:
         repo: https://github.com/swarm-robotics/cosm.git
         dest: "{{ research_root }}/cosm"
         update: yes
         version: feature/172/extra-turtlebot-sensors

     - name: Pull and rebase FORDYCA
       ansible.builtin.git:
         repo: https://github.com/swarm-robotics/fordyca.git
         dest: "{{ research_root }}/fordyca"
         update: yes
         version: refactor/734/COSM172-flowdown

 - name: Pull and rebase ROSbridge
   import_playbook: rosbridge-update.yaml
