---
 - name: Get turtlebot config
   include_vars: vars/turtlebot-config.yaml
   when: inventory_hostname in groups['turtlebots']

 - name: Get develserver config
   include_vars: vars/develserver-config.yaml
   when: inventory_hostname in groups['develservers']

 - name: Rebuild ROSBridge
   shell: cd "{{ research_root }}/rosbridge" && catkin build
   args:
     executable: /bin/bash
