---
 - name: Configure turtlebot build environment
   hosts: [turtlebots]
   tasks:
     - name: Download OpenCR firmware
       get_url:
          url: https://github.com/ROBOTIS-GIT/OpenCR-Binaries/raw/master/turtlebot3/ROS1/latest/opencr_update.tar.bz2
          dest: /tmp/opencr_update.tar.bz2

     - name: Extract new OpenCR firmware
       unarchive:
         src: /tmp/opencr_update.tar.bz2
         dest: /tmp/
         remote_src: yes

     - name: Update OpenCR firmware
       shell: cd /tmp/opencr_update && ./update.sh /dev/ttyACM0 burger_noetic.opencr

     - name: Install apt packages
       apt:
         pkg:
           - dphys-swapfile
         state: latest

     # The stock .bashrc only sets this if in an interactive shell, which ssh
     # commands are not. Needed so executables from python packages can be found.
     - name: Update .bashrc $PATH
       lineinfile:
         path: $HOME/.bashrc
         insertbefore: BOF
         line: if [ -d "$HOME/.local/bin" ] ; then PATH="$HOME/.local/bin:$PATH"; fi

     - name: Lookup ROS1 config
       ansible.builtin.include_vars:
         file: vars/ros1-config.yaml

     - name: Update .bashrc for ROS
       lineinfile:
         path: $HOME/.bashrc
         insertbefore: BOF
         line: "source /opt/ros/{{ ros1_distro }}/setup.bash"
