---
 - name: Playbook to configure turtlebot build environment
   hosts: [turtlebots]
   tasks:
     - name: Download OpenCR firmware
       get_url:
          url: https://github.com/ROBOTIS-GIT/OpenCR-Binaries/raw/master/turtlebot3/ROS1/latest/opencr_update.tar.bz2 dest=/tmp/opencr_update

     - name: Extract OpenCR firmware
       unarchive:
         src: foo
         dest: /tmp/opencr_update

     - name: Update OpenCR firmware
       shell: /tmp/opencr_update/update.sh /dev/ttyACM0 /tmp/opencr_update.burger_noetic.opencr

     - name: Install apt packages
       apt:
         pkgs:
           - dphys-swapfile
         state: latest
         update_cache: true
