---
 - name: Pull project updates to turtlebots
   hosts: [turtlebots]
   tasks:
     - name: Get turtlebot config
       include_vars: vars/turtlebot-config.yaml
       when: inventory_hostname in groups['turtlebots']

     - name: Get develserver config
       include_vars: vars/develserver-config.yaml
       when: inventory_hostname in groups['develservers']

     # - name: Pull and rebase RCSW
     #   git:
     #     repo: https://github.com/swarm-robotics/rcsw.git
     #     dest: "{{ research_root }}/rcsw"
     #     update: yes
     #     version: devel

     # - name: Pull and rebase RCPPSW
     #   git:
     #     repo: https://github.com/swarm-robotics/rcppsw.git
     #     dest: "{{ research_root }}/rcppsw"
     #     update: yes
     #     version: devel

     - name: Pull and rebase COSM
       git:
         repo: https://github.com/swarm-robotics/cosm.git
         dest: "{{ research_root }}/cosm"
         update: yes
         version: bugfix/177/ROS-multirobot-bringup-failure

     - name: Pull and rebase FORDYCA
       git:
         repo: https://github.com/swarm-robotics/fordyca.git
         dest: "{{ research_root }}/fordyca"
         update: yes
         version: devel

     - name: Pull and rebase ROSbridge
       include_tasks: rosbridge-init.yaml


 - name: Rebuild project code on turtlebots
   hosts: [turtlebots]
   tasks:
     # - name: Rebuild RCSW
     #   make:
     #     chdir: $HOME/research/rcsw/build
     #     target: install

     # - name: Rebuild RCPPSW
     #   make:
     #     chdir: $HOME/research/rcppsw/build
     #     target: install

     - name: Force re-running COSM cmake
       ansible.builtin.file:
         path: "{{ research_root }}/cosm/CMakeLists.txt"
         state: touch

     - name: Lookup ROS1 config
       ansible.builtin.include_vars:
         file: vars/ros1-config.yaml

     - name: Rebuild COSM
       make:
         chdir: "{{ research_root }}/cosm/build"
         target: install

     - name: Force re-running FORDYCA cmake
       ansible.builtin.file:
         path: "{{ research_root }}/fordyca/CMakeLists.txt"
         state: touch

     - name: Rebuild FORDYCA
       make:
         chdir: "{{ research_root }}/fordyca/build"
         target: install

     - name: Rebuild ROSBridge
       include_tasks: rosbridge-build.yaml
